public class Movies
{
	 public static void main(String[] args)
	 {
		 String[] moviename={"appu","abhay","mayura","googly","ajay","jachie","raam","raj","arasu","power","mytri","rana vikrama","anjani putra","anna bond","bindass","pritvi","milana","aakash","yarivanu","vamshi","huduguru","doddamane hudga","rajkumar","natasarvabowma","hosa belaku","chalisuva modagalu","abhi","vasantha geeta","pramda kanike","hosa belaku","bhakta prahalada","lasya"};
		 System.out.println("list of kannada movie names:");
		  System.out.println("moviename1:"+moviename[0]);
		 System.out.println("moviename2:"+moviename[1]);
		 System.out.println("moviename3:"+moviename[2]);
		 System.out.println("moviename4:"+moviename[3]);
		 System.out.println("moviename5:"+moviename[4]);
		 System.out.println("moviename6:"+moviename[5]);
		 System.out.println("moviename7:"+moviename[6]);
		 System.out.println("moviename8:"+moviename[7]);
		 System.out.println("moviename9:"+moviename[8]);
		 System.out.println("moviename10:"+moviename[9]);
		 System.out.println("moviename11:"+moviename[10]);
		 System.out.println("moviename12:"+moviename[11]);
		 System.out.println("moviename13:"+moviename[12]);
		 System.out.println("moviename14:"+moviename[13]);
		 System.out.println("moviename15:"+moviename[14]);
		 System.out.println("moviename16:"+moviename[15]);
		 System.out.println("moviename17:"+moviename[16]);
		 System.out.println("moviename18:"+moviename[17]);
		 System.out.println("moviename19:"+moviename[18]);
		 System.out.println("moviename20:"+moviename[19]);
		 System.out.println("moviename21:"+moviename[20]);
		 System.out.println("moviename22:"+moviename[21]);
		 System.out.println("moviename23:"+moviename[22]);
		 System.out.println("moviename24:"+moviename[23]);
		 System.out.println("moviename25:"+moviename[24]);
		 System.out.println("moviename26:"+moviename[25]);
		 System.out.println("moviename27:"+moviename[26]);
		 System.out.println("moviename28:"+moviename[27]);
		 System.out.println("moviename29:"+moviename[28]);
		 System.out.println("moviename30:"+moviename[29]);
		 System.out.println("moviename31:"+moviename[30]);
		 System.out.println("moviename32:"+moviename[31]);
		 moviename[0]="ramachari";
		 moviename[1]="rajahuli";
		 moviename[2]="gajakesari";
		 moviename[3]="drama";
		 moviename[4]="raki";
		 moviename[5]="lucky";
		 moviename[6]="moggina manasu";
		 moviename[7]="master piece";
		 moviename[8]="kgf";
		 moviename[9]="rajadhani";
		 moviename[10]="kotigobba";
		 moviename[11]="kantara";
		 moviename[12]="dia";
		 moviename[13]="love moctail";
		 moviename[14]="bell bottom";
		 moviename[15]="pailwan";
		 moviename[16]="rangitaranga";
		 moviename[17]="charlie";
		 moviename[18]="kirik party";
		 moviename[19]="beema";
		 moviename[20]="soma";
		 moviename[21]="rama";
		 moviename[22]="shama";
		 moviename[23]="mungaru male";
		 moviename[24]="chamak";
		 moviename[25]="modala sala";
		 moviename[26]="eradu hrudayagalu";
		 moviename[27]="lucia";
		 moviename[28]="navagraha";
		 moviename[29]="rana";
		 moviename[30]="ekloveya";
		 moviename[31]="galipata";
		 System.out.println("updated movie names:");
		 System.out.println("moviename1:"+moviename[0]);
		 System.out.println("moviename2:"+moviename[1]);
		 System.out.println("moviename3:"+moviename[2]);
		 System.out.println("moviename4:"+moviename[3]);
		 System.out.println("moviename5:"+moviename[4]);
		 System.out.println("moviename6:"+moviename[5]);
		 System.out.println("moviename7:"+moviename[6]);
		 System.out.println("moviename8:"+moviename[7]);
		 System.out.println("moviename9:"+moviename[8]);
		 System.out.println("moviename10:"+moviename[9]);
		 System.out.println("moviename11:"+moviename[10]);
		 System.out.println("moviename12:"+moviename[11]);
		 System.out.println("moviename13:"+moviename[12]);
		 System.out.println("moviename14:"+moviename[13]);
		 System.out.println("moviename15:"+moviename[14]);
		 System.out.println("moviename16:"+moviename[15]);
		 System.out.println("moviename17:"+moviename[16]);
		 System.out.println("moviename18:"+moviename[17]);
		 System.out.println("moviename19:"+moviename[18]);
		 System.out.println("moviename20:"+moviename[19]);
		 System.out.println("moviename21:"+moviename[20]);
		 System.out.println("moviename22:"+moviename[21]);
		 System.out.println("moviename23:"+moviename[22]);
		 System.out.println("moviename24:"+moviename[23]);
		 System.out.println("moviename25:"+moviename[24]);
		 System.out.println("moviename26:"+moviename[25]);
		 System.out.println("moviename27:"+moviename[26]);
		 System.out.println("moviename28:"+moviename[27]);
		 System.out.println("moviename29:"+moviename[28]);
		 System.out.println("moviename30:"+moviename[29]);
		 System.out.println("moviename31:"+moviename[30]);
		 System.out.println("moviename32:"+moviename[31]);
	 }
}
