public class Movies
{
	 public static void main(String[] args)
	 {
		 String[] moviename={"appu","abhay","mayura","googly","ajay","jachie","raam","raj","arasu","power","mytri","rana vikrama","anjani putra","anna bond","bindass","pritvi","milana","aakash","yarivanu","vamshi","huduguru","doddamane hudga","rajkumar","natasarvabowma","hosa belaku","chalisuva modagalu","abhi","vasantha geeta","pramda kanike","hosa belaku","bhakta prahalada"};
		 moviename[0]="ramachari";
		 moviename[1]="rajahuli";
		 moviename[2]="gajakesari";
		 moviename[3]="drama";
		 moviename[4]="raki";
		 moviename[5]="lucky";
		 moviename[6]="moggina manasu";
		 moviename[7]="master piece";
		 moviename[8]="kgf";
		 moviename[9]="rajadhani";
		 moviename[10]="kotigobba";
		 moviename[11]="kantara";
		 moviename[12]="dia";
		 moviename[13]="love moctail";
		 moviename[14]="bell bottom";
		 moviename[15]="pailwan";
		 moviename[16]="rangitaranga";
		 moviename[17]="charlie";
		 moviename[18]="kirik party";
		 moviename[19]="beema";
		 moviename[20]="soma";
		 moviename[21]="rama";
		 moviename[22]="shama";
		 moviename[23]="mungaru male";
		 moviename[24]="chamak";
		 moviename[25]="modala sala";
		 moviename[26]="eradu hrudayagalu";
		 moviename[27]="lucia";
		 moviename[28]="navagraha";
		 moviename[29]="rana";
		 moviename[30]="ekloveya";
		 moviename[31]="galipata";
		 System.out.println("moviename1:"+moviename);
		 System.out.println("moviename2:"+moviename);
		 System.out.println("moviename3:"+moviename);
		 System.out.println("moviename4:"+moviename);
		 System.out.println("moviename5:"+moviename);
		 System.out.println("moviename6:"+moviename);
		 System.out.println("moviename7:"+moviename);
		 System.out.println("moviename8:"+moviename);
		 System.out.println("moviename9:"+moviename);
		 System.out.println("moviename10:"+moviename);
		 System.out.println("moviename11:"+moviename);
		 System.out.println("moviename12:"+moviename);
		 System.out.println("moviename13:"+moviename);
		 System.out.println("moviename14:"+moviename);
		 System.out.println("moviename15:"+moviename);
		 System.out.println("moviename16:"+moviename);
		 System.out.println("moviename17:"+moviename);
		 System.out.println("moviename18:"+moviename);
		 System.out.println("moviename19:"+moviename);
		 System.out.println("moviename20:"+moviename);
		 System.out.println("moviename21:"+moviename);
		 System.out.println("moviename22:"+moviename);
		 System.out.println("moviename23:"+moviename);
		 System.out.println("moviename24:"+moviename);
		 System.out.println("moviename25:"+moviename);
		 System.out.println("moviename26:"+moviename);
		 System.out.println("moviename27:"+moviename);
		 System.out.println("moviename28:"+moviename);
		 System.out.println("moviename29:"+moviename);
		 System.out.println("moviename30:"+moviename);
		 System.out.println("moviename31:"+moviename);
	 }
}